vector_store:
  name: 'milvus'
  url: 'http://localhost:19530'
  nlist: 64
  nprobe: 16

llm:
  server_url: ''
  model_name: 'ensemble'
  model_engine: 'nvidia-ai-endpoints'
  model_name_pandas_ai: 'ai-mixtral-8x7b-instruct'

text_splitter:
  model_name: 'Snowflake/snowflake-arctic-embed-l'
  chunk_size: 510
  chunk_overlap: 200

embeddings:
  model_name: 'snowflake/arctic-embed-l'
  model_engine: 'nvidia-ai-endpoints'
  dimensions: 1024
  server_url: ''

retriever:
  top_k: 4
  score_threshold: 0.25
  nr_url: 'http://retrieval-ms:8000'
  nr_pipeline: 'ranked_hybrid'

prompts:
  chat_template: "You are a helpful, respectful and honest assistant.\
    Always answer as helpfully as possible, while being safe.\
    Please ensure that your responses are positive in nature."
  rag_template: "<s>[INST] <<SYS>>\
    Use the following context to answer the user's question. If you don't know the answer,\
    just say that you don't know, don't try to make up an answer.\
    <</SYS>>\
    <s>[INST] Context: {context_str} Question: {query_str} Only return the helpful\
    answer below and nothing else. Helpful answer:[/INST]"
  multi_turn_rag_template:
    "You are a document chatbot. Help the user as they ask questions about documents.\
    User message just asked: {input}\n\n\
    For this, we have retrieved the following potentially-useful info: \
    Conversation History Retrieved:\n{history}\n\n\
    Document Retrieved:\n{context}\n\n\
    Answer only from retrieved data. Make your response conversational."
