name: Deploy App Into Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: vsejdtreyvcnevkkffiq

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - name: "Migrate"
        run: supabase db push
        working-directory: ./apps/api/src
      - name: "User function"
        run: supabase functions deploy user --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
      - name: "App function"
        run: supabase functions deploy app --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
      - name: "Secrets function"
        run: supabase functions deploy secrets --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
