name: Deploy App Into Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      PROJECT_ID: vsejdtreyvcnevkkffiq

    steps:
      - uses: actions/checkout@v3

      - name: Set up Supabase
        uses: supabase/setup-cli@v1.1.5
          
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/apps/app
          
      - name: Link
        run: supabase link --password $DB_PASSWORD --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
        
      - name: Set secrets
        run: |
          supabase secrets set MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
          supabase secrets set SMTP_HOST=$SMTP_HOST
          supabase secrets set SMTP_PORT=$SMTP_PORT
          supabase secrets set SMTP_USER=$SMTP_USER
          supabase secrets set SMTP_PASS=$SMTP_PASS
        working-directory: ./apps/api/src
          
      - name: Migrate
        run: supabase db push --password $DB_PASSWORD
        working-directory: ./apps/api/src
        
      - name: User function
        run: supabase functions deploy user --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
        
      - name: App function
        run: supabase functions deploy app --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
        
      - name: Secrets function
        run: supabase functions deploy secrets --project-ref $PROJECT_ID
        working-directory: ./apps/api/src
