name: Deploy App Into Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    
    strategy:
      matrix:
        node-version: [16.x]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/apps/app
          
      - name: Migrate
        run: npx nx run api:migrate
        
      - name: Upload api to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fuoco-appdev-api"
          entrypoint: https://deno.land/std/http/file_server.ts
          root: apps/api/src
